### ISSUE TITLE
Define an efficient process for model evaluation

### ISSUE THREAD

**Issue by nosqlgeek** [nosqlgeek/ai-meets-museum#14]

**Comment by stephanschorer** [comment]
[model_score_vales.txt](https://github.com/nosqlgeek/ai-meets-museum/files/11321901/model_score_vales.txt)
[model_score_values2.txt](https://github.com/nosqlgeek/ai-meets-museum/files/11321902/model_score_values2.txt)

**Comment by stephanschorer** [comment]
vorerst ResNet, allerdings noch weitere evaluation notwendig

**Comment by Markus2713** [comment]
Modell Evaluierung:
[Modell_evaluierung.xlsx](https://github.com/nosqlgeek/ai-meets-museum/files/11406112/Modell_evaluierung.xlsx)
--> ResNet niedrigster score
