### ISSUE TITLE
showcase Platform

### ISSUE THREAD

**Issue by cwenzl** [nosqlgeek/ai-meets-museum#22]
- [x] Registration and activation for editing the showcase (Deadline 23.04.2023)
- [x] Creation of the showcase frame (Deadline 02.05.2023)
- [x] Submission of the showcase to the project supervisor (Deadline 04.06.2023)
- [x] Editing Moodle survey for informed consent (Deadline 04.06.2023)
- [x] Completion and publication of the showcase on website (Deadline 11.06.2023)

**Information about the showcase:**
Format components of the Showcase
The showcase is composed of the following parts
1. short, concise project name (Important!)
2. short description, 1-2 lines
3. detailed project description
4. images, videos/animations/screencasts, project poster
5. project data (project title, course of study, semester, project participants (first name,
surname), supervisor (first name, surname), project partner (name).

The showcase can contain static elements as well as dynamic components
- Static elements: text, image
- Dynamic elements: video (YouTube, Vimeo), screencast, ...

**Comment by stephanschorer** [comment]
finished showcase can be viewed at:
https://showcase.informatik.hs-augsburg.de/sose-2023/ai-meets-museum
