### ISSUE TITLE
design data model

### ISSUE THREAD

**Issue by LukasWeber2000** [nosqlgeek/ai-meets-museum#25]

**Comment by LukasWeber2000** [comment]
- [ ] evaluate image storage location
- [ ] define data strucutre
- [ ] implement strucutre
- [ ] convert data into new model

**Comment by LukasWeber2000** [comment]
![01_DB_Entwurf_AI_TOOL](https://user-images.githubusercontent.com/50518106/233985081-d5e54e7d-223f-4ad1-a69b-14f7a9a766d2.jpg)

**Comment by LukasWeber2000** [comment]
Zwischenstand des ersten Entwurfs für unsere Datenmodell

**Comment by stephanschorer** [comment]
Entwurf für SQL verworfen - Umstieg auf Redis DB

**Comment by stephanschorer** [comment]
JSON Format definiert (siehe Kommentar unten)
Tensoren werden nachträglich im Feld vectorfield abgelegt.

Zunächst hatten wir das Problem, dass die KNN Search auf ein JSON Feld nicht möglich war, da die Suchfunktion keine Ergebnisse zurückliefert.
Da wir den Code von unseren Testszenarien übernommen hatten, wo wir die Vectoren als Hash Werte in der Redis DB abgelegt haben und dieses Feld in der KNN Search direkt referenziert werden konnte, hatten wir zunächst einige Schwierigkeiten das richtige Feld im JSON Feld in der Suche anzugeben. Da im redis-py Module nicht dieselben Befehle unterstützt beziehungsweise Umwege notwendig sind, mussten wir zunächst einen Alias für das Vector Feld erstellen.
Somit haben wir dem JSON Feld $.vector einen Alias zugewiesen, welchen wir dann im Anschluss in der KNN Suche als Felddeklaration verwenden konnten.
