### ISSUE TITLE
Redis Json DB for data

### ISSUE THREAD

**Issue by LukasWeber2000** [nosqlgeek/ai-meets-museum#29]
über Redis JSON Format informieren
Nachfolge Task von #25

**Comment by stephanschorer** [comment]
aktueller Stand des JSON Formats:
[
 {
  "ObjektId": ,
  "Bezeichnung": ,
  "InventarNr": ,
  "Material": ,
  "Beschreibung": ,
  "TrachslerNr": ,
  "Zeitstempel": 1683574753.0378451
 },
...
]

- [ ] Ancestors fehlen aktuell noch

**Comment by stephanschorer** [comment]
obiges Format wurde beibehalten, zusätzlich wurde das Feld BildNr hinzugefügt, damit das lokale Bild schneller referenziert werden kann
