### ISSUE TITLE
Organize final on-site visit in Krumbach

### ISSUE THREAD

**Issue by nosqlgeek** [nosqlgeek/ai-meets-museum#33]
@mprede Would June the 16th work for you and the students?

**Comment by nosqlgeek** [comment]
Additional tasks:

* Create a press release
* Invite the press to the Museum
* Afterwards a meeting at Stueckwerk Krumbach with M.H., too

**Comment by stephanschorer** [comment]
Projektabgabe erfolgreich abgeschlossen

Nochmals ein Dankeschön an @nosqlgeek und das Heimat Museum in Krumbach für die Unterstützung
