### ISSUE TITLE
Mosaik Bild erstellen

### ISSUE THREAD

**Issue by TPBmidge** [nosqlgeek/ai-meets-museum#39]
Unser Ziel ist es mit den vorhandenen Bildern ein Mosaik Bild zu erstellen, um es auf den kommenden Präsentationen zu verwenden

**Comment by stephanschorer** [comment]
Da die verfügbaren Software Tools unsere Anforderungen nicht erfüllen konnten, wurde ein eigenes Python Skript erstellt, um benutzerdefinierte Mosaik Bilder zu generieren.

Falls Zugriff zum Skript benötigt wird, bitte @SuguruTokawa kontaktieren
