### ISSUE TITLE
Präsentation für Projekttag planen

### ISSUE THREAD

**Issue by TPBmidge** [nosqlgeek/ai-meets-museum#40]
- [x] Präsentation in PP
- [x] Mosaik Bilder erstellen für Plakat
- [x] Plakate gestalten
- [x] Plakate drucken
- [x] Pitch durchsprechen und entsprechend planen und proben

**Comment by stephanschorer** [comment]
Projektabgabe wurde vor Ort am Museum durchgeführt.
Im Anschluss wurde es erneut beim Projekt Tag an der Technischen Hochschule Augsburg vorgezeigt.
