### ISSUE TITLE
Clean the data

### ISSUE THREAD

**Issue by nosqlgeek** [nosqlgeek/ai-meets-museum#8]
The source/test data is currently stored in a relational database. We will need to perform some data cleansing before this data can be used for training purposes. One idea could be to use Pandas dataframes to operate on exported CSV files. We could then use Jupyter notebooks to visualize the results of the data analysis.

**Comment by TPBmidge** [comment]
Mit Pandas wurden die CSV-Dateien in Dataframes überführt und Reformatiert.
